// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_CanvasItem.cpp"
#include "UVLADIE3JM/moc_PreferencesManager.cpp"
#include "UVLADIE3JM/moc_ProjectModel.cpp"
#include "UVLADIE3JM/moc_TestCanvas.cpp"
